### ISSUE TITLE
Do not warn if ConfigureAwait(true) is specified

### ISSUE THREAD

**Issue by martinbu** [cincuranet/ConfigureAwaitChecker#16]
It would be great, if the analyzer do not show a warning, if a ConfigureAwait(true) is already set, to also be able to use it in UI projects, where it is sometimes intended to use ConfigureAwait(true).

What do you mean?

**Comment by cincuranet** [comment]
I personally don't agree with that. The `ConfigureAwait(true)` is what's default behavior and hence it's just keystrokes wasted. 

And passing the `true`, might also mean, the person made a mistake and instead of `false` wrote `true`. :\

**Comment by pmiossec** [comment]
I agree with @martinbu . I think it's strange (and boring :( ) to warn if you intentionally set ` ConfigureAwait(true)`. We have some case here in our projects (wpf and some asp.net) for some reasons...

>I personally don't agree with that. The ConfigureAwait(true) is what's default behavior and hence it's just keystrokes wasted.

If someone set `ConfigureAwait(true)` and especially because that is the default, we could expect that this is for a reason. So, IMHO, the analyzer should not warn.

>And passing the true, might also mean, the person made a mistake and instead of false wrote true. :\

I'm not sure that the analyzer should have the goal to save everyone from their mistakes.
We just want to prevent an oversight to happen and let the developer choose conscientiously if he should set it `true` or `false`....

I will be pleased if you could reconsider your point of view...

**Comment by cincuranet** [comment]
I would happily reconsider, when somebody provides me strong, not
personal, argument it should behave like that, cons/pros included. At
the moment I'm not convinced.

**Comment by pmiossec** [comment]
For those interested by this feature, could you have a look to #18 ?
